version: "3.9"

services:

  apache:
    volumes:
      - ./src:/var/www/src

  php:
    build: 
      args:
        - XDEBUG_INSTALL=${XDEBUG_INSTALL}
    volumes:
      - ./src:/var/www/src
      - ./.docker/php/conf.d/xdebug_v${XDEBUG_MAJOR_VERSION}.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
