version: "3.9"

services:

  apache:
    volumes:
      - ./src:/var/www/src

  php:
    build: 
      args:
        - XDEBUG_INSTALL=${XDEBUG_INSTALL}
    volumes:
      - ./src:/var/www/src
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    extra_hosts:
      # https://stackoverflow.com/questions/31324981/how-to-access-host-port-from-docker-container/43541732#43541732
      - "host.docker.internal:host-gateway"
