version: '3.9'

services:

  apache:
    container_name: ${APPLICATION_NAME}_webserver
    build:
      context: .
      dockerfile: ./.docker/webserver/Dockerfile
    depends_on:
      - php
    networks:
      - backend
    expose:
      - ${APACHE_PORT}
    ports:
      - ${APACHE_PORT}:80

  db:
    container_name: ${APPLICATION_NAME}_db
    image: mysql:5.7
    environment:
      - TZ=Europe/Brussels
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_ROOT_USER}
      - MYSQL_PASSWORD=${DB_ROOT_PASSWORD}
    expose:
      - ${DB_PORT}
    networks:
      - backend
    # volumes:
    #   - ./db:/var/lib/mysql
  
  php:
    container_name: ${APPLICATION_NAME}_php
    build: 
      context: .
      dockerfile: ./.docker/php/Dockerfile
      args:
        - APPLICATION_NAME=${APPLICATION_NAME}
        - OS_USERNAME=${OS_USERNAME}
        - OS_USERID=${OS_USERID}
        - PHP_VERSION=${PHP_VERSION}
        - XDEBUG_INSTALL=${XDEBUG_INSTALL}
    depends_on:
      - db
    environment:
      - DB_HOST=${APPLICATION_NAME}_db:${DB_PORT}
      - DB_USER=${DB_CREDENTIAL_USER}
      - DB_PASSWORD=${DB_CREDENTIAL_PASSWORD}
    networks:
      - backend
      - frontend

volumes:
  db_data:
    
networks:
  frontend:
  backend:
